sudo: required
dist: trusty
before_install:
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra
  texlive-fonts-extra texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build WilliamCromarResume.tex
deploy:
  provider: releases
  api_key:
    secure: LEyGERrOrW1EAIVECtI4+z1RbRwohnI2IS/NY+bxs7I7LmaMB2SdXBTRwn1dygKuB5oLupIrZPrEWWxfjJf71wxMIIGhop6JUcsYCZdIq9nSfdr33FY12s9CJUHVMmwu9J/PSIUNFlBHFwj+AxSfTx6qQBKTks/fIojlvzLD7Jx0o4aNJQSGGp54oqXWg8LpxY1sV79yO90Vw6JTBsdUpkjYuz7HzDnBpeEnJFvEaH0yshZvJVRjx1e3bh8lZ+Pk8toTkJkMXXcrXI5IKpRnhHVSfJL+kYMzi1d6D/k4TUizkpG6hnlsvZTsTutFZrPdlO6UJGDL1+QC23J/zhREmNyLp0U8RhyjpOzhnqhizCQsLQN979XzNYHXJviU0wywgHj7EvSFJcYtBttj22QfMiyMwP4pwgdinYanonaiT3CPRYXDO1ECIhOdtnK8uJ+91yGcR3+MmiugL00idJFW9ttWSBR+b3Z9C6jqrY0u5LWIK1Oyb7KH7FqjjhRoGGsX9uJDGaY5H0tcaNIh2PG+55jHmQJLQQERkopTP92iHTAARUci1BTLBE5UK5cQhot/Y2iTVMcHWbuZumdlNN0fXDBL7cFHqYZHbARif5Bdngm4eoAVkNtAukK5OoSt7k4+aw7yiINXNsGVEnfigUJIWr320vR0p6rXxyW6JlKBlRM=
  file: _build/WilliamCromarResume.pdf
  skip_cleanup: true
  on:
    repo: will-cromar/resume
